# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1C1D1E)
$foreground = rgb(F8F6F5)
$color0 = rgb(434345)
$color1 = rgb(444548)
$color2 = rgb(8C2F2A)
$color3 = rgb(6C6A6B)
$color4 = rgb(706A68)
$color5 = rgb(A6A2A1)
$color6 = rgb(B0ACAA)
$color7 = rgb(ECEAE8)
$color8 = rgb(A6A3A2)
$color9 = rgb(5B5B5F)
$color10 = rgb(BB3F38)
$color11 = rgb(908E8F)
$color12 = rgb(968D8B)
$color13 = rgb(DED9D6)
$color14 = rgb(EBE5E2)
$color15 = rgb(ECEAE8)
