# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

# you can choose themes from $HOME/.config/kitty/kitty-themes/
include ./kitty-themes/Alucard.conf
#
# font_family FantasqueSansM Nerd Font Mono Bold
# font_size 16.0
# bold_font auto
# italic_font auto
# bold_italic_font auto
#
# background_opacity 0.9
# dynamic_background_opacity 1
# confirm_os_window_close 0

# Animated cursor
# cursor_trail 1

# change to x11 or wayland or leave auto
# linux_display_server auto
#
# scrollback_lines 2000
# wheel_scroll_min_lines 1
#
# enable_audio_bell no
#
# window_padding_width 4
#
# selection_foreground none
# selection_background none
#
# foreground #000000
# background #dddddd
# cursor #000000

# configs/kitty/kitty.conf
#    __ ___ __  __
#   / //_(_) /_/ /___ __
#  / ,< / / __/ __/ // /
# /_/|_/_/\__/\__/\_, /
#                /___/
#
# Configuration


font_family                 JetBrainsMono Nerd Font


font_size                   12


bold_font                   auto


italic_font                 auto


bold_italic_font            auto


remember_window_size        no


initial_window_width        950


initial_window_height       500


cursor_blink_interval       0.5


cursor_stop_blinking_after  1


scrollback_lines            2000


wheel_scroll_min_lines      1


enable_audio_bell           no


window_padding_width        10


hide_window_decorations     yes


background_opacity          0.5


dynamic_background_opacity  no


confirm_os_window_close     0


selection_foreground        none


selection_background        none

# Animated cursor follows text
# include $HOME/.config/ml4w/settings/kitty-cursor-trail.conf

# Include wallpaper colors
include kitty-themes

 include ./colors/colors.conf

include ~/.cache/wal/colors-kitty.conf

# Include Custom Configuration

# Create the file custom.conf in ~/.config/kitty to overwrite the default configuration
# include ./custom.conf
single_instance = yes
shell_integration disabled
