# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F8F6F5
background         #1C1D1E
cursor             #DA9A96

active_tab_foreground     #1C1D1E
active_tab_background     #F8F6F5
inactive_tab_foreground   #F8F6F5
inactive_tab_background   #1C1D1E

active_border_color   #F8F6F5
inactive_border_color #1C1D1E
bell_border_color     #444548

color0      #434345
color1		#444548
color2		#8C2F2A
color3		#6C6A6B
color4		#706A68
color5		#A6A2A1
color6		#B0ACAA
color7		#ECEAE8
color8		#A6A3A2
color9		#5B5B5F
color10		#BB3F38
color11		#908E8F
color12		#968D8B
color13		#DED9D6
color14		#EBE5E2
color15		#ECEAE8
